# Assignment 1
The objective of this assignment is to enhance your proficiency with the NumPy library by engaging in a series of tasks encompassing diverse operations, statistical analyses, and indexing/slicing procedures. Through the completion of these tasks, you are expected to reinforce your understanding of NumPy functionalities and sharpen your skills in leveraging the library for effective data manipulation.

**Instructions:**
  - Do not remove comments such as # Task 1.1,# Task 1.2 etc. Provide your answers bellow these comments.
  - Use the provided variable names for your answers.
  - If the question is related to numpy operations, you are not allowed to use for loops.


**Task 1: Basic NumPy Operations (10 points)**
1. Create a NumPy array with the values `[1, 2, 3, 4, 5]`. Name this array `arr1`. (1pt)
2. Create another NumPy array with the values `[6, 7, 8, 9, 10]`. Name this array `arr2`. (1pt)
3. Perform element-wise addition, subtraction, multiplication, and division on `arr1` and `arr2`. Store the results in new arrays. (8pts)

In [1]:
import numpy as np

# Task 1.1
arr1 = np.array([1, 2, 3, 4, 5])

# Task 1.2
arr2 = np.array([6, 7, 8, 9, 10])

# Task 1.3
addition_result = arr1 + arr2
subtraction_result = arr1 - arr2
multiplication_result = arr1 * arr2
division_result = arr1 / arr2

**Task 2: Statistical Analysis (20 points)**
1. Create a random NumPy array with 100 elements sampled from a normal distribution with mean 50 and standard deviation 10. Name this array `data`. (5pts)
2. Calculate and print the mean, median, and standard deviation of the `data` array. (5pts)
3. Reshape the `data` array into a 10x10 matrix. (5pts)
4. Find the minimum and maximum values in each row and each column of the reshaped matrix. (5pts)

In [2]:
# Task 2.1
data = np.random.normal(50, 10, 100)

# Task 2.2
mean_value = np.mean(data)
median_value = np.median(data)
std_deviation =np.std(data)

# Task 2.3
reshaped_data = np.reshape(data, (10,10))

# Task 2.4
min_values_by_row = np.min(reshaped_data, axis=1)
max_values_by_row = np.max(reshaped_data, axis=1)
min_values_by_col = np.min(reshaped_data, axis=0)
max_values_by_col = np.max(reshaped_data, axis=0)





**Task 3: NumPy Indexing and Slicing (35 points)**
1. Create a NumPy array with values `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`. Name this array `arr3`. (1pt)
2. Print the even elements of `arr3`. (10pts)
3. Print the elements greater than 5 in `arr3`. (10pts)
4. Reshape `arr3` into a 2x5 matrix. (4pts)
5. Extract the second column of the reshaped matrix. (10pts)

In [3]:
# Task 3.1
arr3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_elems = arr3[arr3 % 2 == 0]

# Task 3.2
elements_greater_than_5 = arr3[arr3 > 5]

# Task 3.3
reshaped_arr3 = np.reshape(arr3, (2, 5))

# Task 3.4
second_column = reshaped_arr3[0:3, 1]


 **Task 4: Axis Operations: (35pts)**
    
1. Create a 2D NumPy array with shape (4, 5) containing random integers. (5pts)
2. Calculate the sum of each column and find the column index with the maximum sum. (10pts)
3. Calculate the mean of each row and find the row index with the minimum mean. (10pts)
4. Normalize the values of each column by subtracting the mean and dividing by the standard deviation of the column. (10pts)

In [4]:
# Task 4.1 
array_2d = np.random.random_integers(0, 10, size=(4, 5))
print(array_2d)
# Task 4.2
column_sums = array_2d.sum(axis=0)
max_sum_column_index = np.argmax(array_2d.sum(axis=0))

print(column_sums)
print(max_sum_column_index)

# Task 4.3
row_means = 1
min_mean_row_index = 1

# Task 4.4
normalized_array = 1

[[ 3  1  7  5  1]
 [ 9  3 10  1  2]
 [ 6  9  9  2  9]
 [ 8  5  7  7  0]]
[26 18 33 15 12]
[26 18 33 15 12]


C:\Users\yugpa\AppData\Local\Temp\ipykernel_17732\840634757.py:2: DeprecationWarning: This function is deprecated. Please call randint(0, 10 + 1) instead
  array_2d = np.random.random_integers(0, 10, size=(4, 5))
